INSERT INTO book (name, author, category) VALUES
('The Waste Land', 'T.S. Eliot', 'POETRY'),
('The Divine Comedy', 'Dante Alighieri', 'POETRY'),
('THE ESSENTIAL RUMI ', 'RUMI', 'POETRY'),
( 'THE ESSENTIAL RUMI Vol. 2', 'RUMI', 'POETRY'),
( 'THE COMPLETE SONNETS AND POEMS ', 'WILLIAM SHAKESPEARE', 'POETRY'),
( 'JOHN DONNE’S POETRY ', 'JOHN DONNE', 'POETRY'),
( 'ON LOVE AND BARLEY: HAIKU OF BASHO ', 'BASHO', 'POETRY'),
( 'SONGS OF INNOCENCE AND EXPERIENCE ', 'WILLIAM BLAKE', 'POETRY'),
( 'LYRICAL BALLADS', 'WILLIAM WORDSWORTH', 'POETRY'),
( 'SELECTED POETRY ', 'OHN KEATS', 'POETRY'),
( 'LEAVES OF GRASS ', 'WALT WHITMAN', 'POETRY'),
( 'GOBLIN MARKET AND OTHER POEMS ', 'CHRISTINA ROSSETTI', 'POETRY'),
( 'Hamlet ', 'WILLIAM SHAKESPEARE ', 'LITERATURE'),
( 'The Great Gatsby', 'F. Scott', 'LITERATURE'),
( 'Nineteen Eighty-Four', 'George Orwell', 'LITERATURE'),
( 'The Catcher in the Rye', 'JD Salinger', 'LITERATURE'),
( 'To Kill a Mockingbird', 'Harper Lee', 'LITERATURE'),
( 'Anna Karenina', 'Leo Tolstoy', 'LITERATURE'),
( 'Moby-Dick', 'Herman Melville', 'LITERATURE'),
( 'Pride and Prejudice', 'Jane Austen', 'LITERATURE'),
( 'Don Quixote', 'Miguel de Cervantes,', 'LITERATURE'),
( 'Things Fall Apart', 'Chinua Achebe', 'LITERATURE'),
( 'Brave New World', 'Aldous Huxley', 'LITERATURE'),
( 'Wuthering Heights', 'Emily Brontë', 'LITERATURE'),
( 'Little Women', 'Louisa May Alcott', 'LITERATURE'),
( 'The Perfectionists: How Precision Engineers Created the Modern World', 'Simon Winchester', 'TECHNICAL'),
( 'The Perfectionists: Vol 2', 'Simon Winchester', 'TECHNICAL'),
( 'The Perfectionists: VOL.3', 'Simon Winchester', 'LITERATURE'),
( 'Race', 'Fyodor Dostoevsky', 'TECHNICAL'),
( 'The Perfectionists:vol 4', 'Simon Winchester', 'POETRY'),
( 'Race After Technology', 'Ruha Benjamin', 'TECHNICAL'),
( 'The Soul of a New Machine', 'Tracy Kidder', 'TECHNICAL'),
( 'The Soul of an Old Machine', 'Tracy Kidder', 'TECHNICAL'),
( 'Race After Technology Vol.2', 'Tracy Kidder', 'TECHNICAL'),
( 'The Soul of XYZ', 'Fyodor Dostoevsky', 'TECHNICAL'),
( 'The Soul', 'Tracy Kidder', 'POETRY'),
( 'Leaning Into the Fall', 'Lane Hayes', 'TECHNICAL'),
( 'Leaning Into the fire', 'Lane Hayes', 'TECHNICAL'),
( 'Leaning Into the Well', 'Lane Hayes', 'FICTION'),
( 'The Soul of a New Machine', 'Tracy Kidder', 'TECHNICAL'),
( 'Life 3.0', 'Max Tegmark', 'TECHNICAL'),
( 'The Innovators', 'Walter Isaacson', 'TECHNICAL'),
( 'The Code: Silicon Valley and the Remaking of America', 'Margaret O Mara', 'TECHNICAL'),
( 'Tech Panic: Why We Shouldnot Fear Facebook and the Future', 'Robby Soave', 'TECHNICAL'),
( 'The Soul of a New Machine Vol.2', 'Fyodor Dostoevsky', 'TECHNICAL'),
( 'Tech Panic: Why We Should Fear Big Data and the Future', 'Robby Soave', 'TECHNICAL'),
( 'Tech Panic', 'Robby Soave', 'LITERATURE'),
( 'A Confederacy of Dunces', 'John Kennedy Toole', 'HUMOUR'),
( 'Catch-22', 'Joseph Heller', 'HUMOUR'),
( 'Me Talk Pretty One Day', 'David Sedaris', 'HUMOUR'),
( 'Bossypants', 'Tina Fey', 'HUMOUR'),
( 'The Ultimate Hitchhiker s Guide', 'Douglas Adams', 'HUMOUR'),
( 'Good Omens', 'Neil Gaiman', 'HUMOUR'),
( 'Bridget Jones s Diary', 'Helen Fielding', 'HUMOUR'),
( 'Born a Crime', 'Trevor Noah', 'HUMOUR'),
( 'Yes Please', 'Amy Poehler', 'HUMOUR'),
( 'Lucky Jim', 'Kingsley Amis', 'HUMOUR'),
( 'Cold Comfort Farm', 'Stella Gibbons', 'HUMOUR'),
( 'C C Farm', 'Stella Gibbons', 'HUMOUR'),
( 'Cold Comfort', 'Stella Gibbons', 'FICTION'),
( 'Cold Farm', 'Stella Gibbons', 'FICTION'),
( 'Big Trouble', 'Tina Fey', 'HUMOUR'),
( 'Priestdaddy', 'Tina Fey', 'HUMOUR'),
( 'The Code of the Woosters', 'Tina Fey', 'HUMOUR'),
( 'High Fidelity', 'Tina Fey', 'HUMOUR'),
( 'Fidelity', 'Tina Fey', 'HUMOUR'),
( 'A Brief History of Time', 'Stephen Hawking', 'SCIENCE'),
( 'A Brief History ', 'Stephen Hawking', 'SCIENCE'),
( 'History of Time', 'Stephen Hawking', 'FICTION'),
( 'Time', 'Stephen Hawking', 'POETRY'),
( 'Cosmos', 'Carl Sagan', 'SCIENCE'),
( 'Silent Spring', 'Rachel Carson', 'SCIENCE'),
( 'The Soul of a New Machine Vol.3', 'Fyodor Dostoevsky', 'SCIENCE'),
( 'The Soul of a New Machine Vol.4', 'Fyodor Dostoevsky', 'SCIENCE'),
( 'The Soul of a New Machine Vol.5', 'Fyodor Dostoevsky', 'SCIENCE'),
( 'The Soul of a New Machine Vol.7', 'Fyodor Dostoevsky', 'HUMOUR'),
( 'The Soul of a New Machine Vol.9', 'Fyodor Dostoevsky', 'POETRY'),
( 'The Selfish Gene', 'Richard Dawkins', 'SCIENCE'),
( 'The Blind Watchmaker', 'Richard Dawkins', 'SCIENCE'),
( 'The Mismeasure of Man', 'Stephen Jay Gould', 'SCIENCE'),
( 'The Grand Design', 'Leonard Mlodinow', 'SCIENCE'),
( 'Bad Science', 'Ben Goldacre', 'SCIENCE'),
( 'The Elegant Universe', 'Brian Greene', 'SCIENCE'),
( 'The Double Helix', 'James D. Watson', 'SCIENCE'),
( 'Freakonomics', 'Steven Levitt,', 'SCIENCE'),
( 'Freakonomics Vol. 2', 'Steven Levitt', 'SCIENCE'),
( 'Freakonomics Vol.3', 'Steven Levitt', 'SCIENCE'),
( 'Freakonomics Vol. 4', 'Steven Levitt', 'HUMOUR'),
( 'Freakonomics Vol.5', 'Steven Levitt', 'FICTION'),
( 'Six easy pieces', 'Richard Feynman', 'SCIENCE'),
( 'Nineteen Eighty-Four', 'George Orwell', 'FICTION'),
( 'Eighty-Four', 'George Orwell', 'FICTION'),
( 'Nineteen Eighty', 'George Orwell', 'FICTION'),
( 'Nineteen Sisty-Four', 'George Orwell', 'HUMOUR'),
( 'Beloved', 'Toni Morrison', 'FICTION'),
( 'The Handmaid s Tale', 'Margaret Atwood,', 'FICTION'),
( 'Anna Karenina', 'Leo Tolstoy', 'FICTION'),
( 'Atonement', 'Ian McEwan', 'FICTION'),
( 'Things Fall Apart', 'Chinua Achebe', 'FICTION'),
( 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'FICTION'),
( 'The  Karamazov', 'Fyodor Dostoevsky', 'FICTION'),
( 'The Brothers', 'Fyodor Dostoevsky,', 'FICTION');