server:
  port: 9090
logging:
  level:
    root: info
    com.vmware.bookmanagement: debug
spring:
  application:
    name: book-management
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookmanagement;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
springdoc:
  api-docs:
    path: /book-api-docs
